# Example 1

## Measure of central tendency

In [2360]:
#created the list into a table format
import pandas as pd
A=pd.DataFrame(data={'values': [1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8]})
A

values
0        1
1        2
2        3
3        1
4        2
5        3
6        4
7        2
8        3
9        5
10       6
11       7
12       8
13       8
14       9
15       8

In [2361]:
#mean using pandas
A.mean()

# To show answer

values    4.5
dtype: float64

In [2362]:
A.describe()

values
count  16.000000
mean    4.500000
std     2.780887
min     1.000000
25%     2.000000
50%     3.500000
75%     7.250000
max     9.000000

In [2363]:
#mean 

import numpy as np
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8]

#using numpy
np.mean(B)

4.5

In [2364]:
print("mean : ", np.mean(B))

mean :  4.5


In [2365]:
#median
#using pandas
A.median()

values    3.5
dtype: float64

In [2366]:
A.describe()

values
count  16.000000
mean    4.500000
std     2.780887
min     1.000000
25%     2.000000
50%     3.500000
75%     7.250000
max     9.000000

In [2367]:
#median
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8]

#using numpy
np.median(B)

3.5

In [2368]:
print("median : ", np.median(B))

median :  3.5


In [2369]:
#using pandas
A.mode()  

values
0       2
1       3
2       8

In [2370]:
#mode
#numpy does not has an attribute mode

In [2371]:
#descriptive statistics
#measure of dispersion
#variance and std deviation

## Measure of Dispersion

### Variance

In [2372]:
#variance
A.var()

values    7.733333
dtype: float64

In [2373]:
#variance
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8]

#using numpy
np.var(B)
     

7.25

In [2374]:
print("Variance : ", np.var(B))

Variance :  7.25


## Standard deviation

In [2375]:
#using pandas
A.std()

values    2.780887
dtype: float64

In [2376]:

#standard deviation
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8]

#using numpy
np.std(B)

2.692582403567252

In [2377]:

print("Variance : ", np.std(B))

Variance :  2.692582403567252


# 5 number Summary


Minimum


1st quartile -Q1


2nd quartile -Q2(Median)



3rd quartile -Q3


Maximum


### Minimum

In [2378]:
#Minimum using pandas

A.min() 


values    1
dtype: int64

In [2379]:

#Minimum
B=[1,2,3,1,2,3,4,5,2,6,7,5,4,8,10]

#using numpy
np.min(B)

1

In [2380]:

print("Minimum : ", np.min(B))

Minimum :  1


## Quartiles

In [2381]:
#using pandas
A.quantile([0.25,0.50,0.75]) 

values
0.25    2.00
0.50    3.50
0.75    7.25

In [2382]:

A.describe()

values
count  16.000000
mean    4.500000
std     2.780887
min     1.000000
25%     2.000000
50%     3.500000
75%     7.250000
max     9.000000

In [2383]:

#quartiles
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8]

#using numpy
np.quantile(B,[0.25,0.50,0.75])

array([2.  , 3.5 , 7.25])

In [2384]:

print("Q1 : ", np.quantile(B,0.25),
      "Q2 : ", np.quantile(B,0.50),
      "Q3 : ", np.quantile(B,0.75))

Q1 :  2.0 Q2 :  3.5 Q3 :  7.25


## Maximum

In [2385]:

#using pandas
A.max()  

values    9
dtype: int64

In [2386]:
#Maximum
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8]

#using numpy
np.max(B)

9

In [2387]:
print("Maximum : ", np.max(B))

Maximum :  9


## Range

In [2388]:
#using pandas
Range = A.max()-A.min()
Range
     

values    8
dtype: int64

In [2389]:

#Range
#using numpy

Ran=np.max(B) - np.min(B)
Ran

8

## IQR

In [2390]:
#using pandas
iqr=A.quantile(0.75)-A.quantile(0.25)
iqr

values    5.25
dtype: float64

In [2391]:

#IQR
#using numpy
IQR = np.quantile(B,0.75)-np.quantile(B,0.25)
IQR

5.25

## QD

In [2392]:
#QD
#using pandas
qd =iqr/2
qd

values    2.625
dtype: float64

In [2393]:

#QD
#using numpy
QD = IQR/2
QD


2.625

# Example 2

## Measure of central tendency

In [2394]:
#created the list into a table format
import pandas as pd
A=pd.DataFrame(data={'values': [1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10]})
A

values
0        1
1        2
2        3
3        1
4        2
5        3
6        4
7        2
8        3
9        5
10       6
11       7
12       8
13       8
14       9
15       8
16       9
17      10

In [2395]:
#mean using pandas
A.mean()

# To show answer

values    5.055556
dtype: float64

In [2396]:
A.describe()

values
count  18.000000
mean    5.055556
std     3.076901
min     1.000000
25%     2.250000
50%     4.500000
75%     8.000000
max    10.000000

In [2397]:
#mean 

import numpy as np
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10]

#using numpy
np.mean(B)

5.055555555555555

In [2398]:
print("mean : ", np.mean(B))

mean :  5.055555555555555


In [2399]:
#median
#using pandas
A.median()

values    4.5
dtype: float64

In [2400]:
A.describe()

values
count  18.000000
mean    5.055556
std     3.076901
min     1.000000
25%     2.250000
50%     4.500000
75%     8.000000
max    10.000000

In [2401]:
#median
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10]

#using numpy
np.median(B)

4.5

In [2402]:
print("median : ", np.median(B))

median :  4.5


In [2403]:
#using pandas
A.mode()  

values
0       2
1       3
2       8

In [2404]:
#mode
#numpy does not has an attribute mode

In [2405]:
#descriptive statistics
#measure of dispersion
#variance and std deviation

## Measure of Dispersion

### Variance

In [2406]:
#variance
A.var()

values    9.46732
dtype: float64

In [2407]:
#variance

In [2408]:
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10]

#using numpy
np.var(B)
     

8.94135802469136

In [2409]:
print("Variance : ", np.var(B))

Variance :  8.94135802469136


## Standard deviation

In [2410]:
#using pandas
A.std()

values    3.076901
dtype: float64

In [2411]:

#standard deviation
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10]

#using numpy
np.std(B)

2.9902103646217535

In [2412]:

print("Variance : ", np.std(B))

Variance :  2.9902103646217535


# 5 number Summary


Minimum


1st quartile -Q1


2nd quartile -Q2(Median)



3rd quartile -Q3


Maximum


### Minimum

In [2413]:
#Minimum using pandas

A.min() 


values    1
dtype: int64

In [2414]:

#Minimum
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10]

#using numpy
np.min(B)

1

In [2415]:

print("Minimum : ", np.min(B))

Minimum :  1


## Quartiles

In [2416]:
#using pandas
A.quantile([0.25,0.50,0.75]) 

values
0.25    2.25
0.50    4.50
0.75    8.00

In [2417]:

A.describe()

values
count  18.000000
mean    5.055556
std     3.076901
min     1.000000
25%     2.250000
50%     4.500000
75%     8.000000
max    10.000000

In [2418]:

#quartiles
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10]

#using numpy
np.quantile(B,[0.25,0.50,0.75])

array([2.25, 4.5 , 8.  ])

In [2419]:

print("Q1 : ", np.quantile(B,0.25),
      "Q2 : ", np.quantile(B,0.50),
      "Q3 : ", np.quantile(B,0.75))

Q1 :  2.25 Q2 :  4.5 Q3 :  8.0


## Maximum

In [2420]:

#using pandas
A.max()  

values    10
dtype: int64

In [2421]:
#Maximum
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10]

#using numpy
np.max(B)

10

In [2422]:
print("Maximum : ", np.max(B))

Maximum :  10


## Range

In [2423]:
#using pandas
Range = A.max()-A.min()
Range
     

values    9
dtype: int64

In [2424]:

#Range
#using numpy

Ran=np.max(B) - np.min(B)
Ran

9

## IQR

In [2425]:
#using pandas
iqr=A.quantile(0.75)-A.quantile(0.25)
iqr

values    5.75
dtype: float64

In [2426]:

#IQR
#using numpy
IQR = np.quantile(B,0.75)-np.quantile(B,0.25)
IQR

5.75

## QD

In [2427]:
#QD
#using pandas
qd =iqr/2
qd

values    2.875
dtype: float64

In [2428]:

#QD
#using numpy
QD = IQR/2
QD


2.875

# Example 3

## Measure of central tendency

In [2429]:
#created the list into a table format
import pandas as pd
A=pd.DataFrame(data={'values': [1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12]})
A

values
0        1
1        2
2        3
3        1
4        2
5        3
6        4
7        2
8        3
9        5
10       6
11       7
12       8
13       8
14       9
15       8
16       9
17      10
18      12

In [2430]:
#mean using pandas
A.mean()

# To show answer

values    5.421053
dtype: float64

In [2431]:
A.describe()

values
count  19.000000
mean    5.421053
std     3.388146
min     1.000000
25%     2.500000
50%     5.000000
75%     8.000000
max    12.000000

In [2432]:
#mean 

import numpy as np
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12]

#using numpy
np.mean(B)

5.421052631578948

In [2433]:
print("mean : ", np.mean(B))

mean :  5.421052631578948


In [2434]:
#median
#using pandas
A.median()

values    5.0
dtype: float64

In [2435]:
A.describe()

values
count  19.000000
mean    5.421053
std     3.388146
min     1.000000
25%     2.500000
50%     5.000000
75%     8.000000
max    12.000000

In [2436]:
#median
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12]

#using numpy
np.median(B)

5.0

In [2437]:
print("median : ", np.median(B))

median :  5.0


In [2438]:
#using pandas
A.mode()  

values
0       2
1       3
2       8

In [2439]:
#mode
#numpy does not has an attribute mode

In [2440]:
#descriptive statistics
#measure of dispersion
#variance and std deviation

## Measure of Dispersion

### Variance

In [2441]:
#variance
A.var()

values    11.479532
dtype: float64

In [2442]:

#variance

In [2443]:
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12]

#using numpy
np.var(B)
     

10.875346260387813

In [2444]:

print("Variance : ", np.var(B))

Variance :  10.875346260387813


## Standard deviation

In [2445]:
#using pandas
A.std()

values    3.388146
dtype: float64

In [2446]:

#standard deviation
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12]

#using numpy
np.std(B)

3.297778989014851

In [2447]:

print("Variance : ", np.std(B))

Variance :  3.297778989014851


# 5 number Summary


Minimum


1st quartile -Q1


2nd quartile -Q2(Median)



3rd quartile -Q3


Maximum


### Minimum

In [2448]:
#Minimum using pandas

A.min() 


values    1
dtype: int64

In [2449]:

#Minimum
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12]

#using numpy
np.min(B)

1

In [2450]:

print("Minimum : ", np.min(B))

Minimum :  1


## Quartiles

In [2451]:
#using pandas
A.quantile([0.25,0.50,0.75]) 

values
0.25     2.5
0.50     5.0
0.75     8.0

In [2452]:

A.describe()

values
count  19.000000
mean    5.421053
std     3.388146
min     1.000000
25%     2.500000
50%     5.000000
75%     8.000000
max    12.000000

In [2453]:

#quartiles
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12]

#using numpy
np.quantile(B,[0.25,0.50,0.75])

array([2.5, 5. , 8. ])

In [2454]:

print("Q1 : ", np.quantile(B,0.25),
      "Q2 : ", np.quantile(B,0.50),
      "Q3 : ", np.quantile(B,0.75))

Q1 :  2.5 Q2 :  5.0 Q3 :  8.0


## Maximum

In [2455]:

#using pandas
A.max()  

values    12
dtype: int64

In [2456]:
#Maximum
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12]

#using numpy
np.max(B)

12

In [2457]:
print("Maximum : ", np.max(B))

Maximum :  12


## Range

In [2458]:
#using pandas
Range = A.max()-A.min()
Range
     

values    11
dtype: int64

In [2459]:

#Range
#using numpy

Ran=np.max(B) - np.min(B)
Ran

11

## IQR

In [2460]:
#using pandas
iqr=A.quantile(0.75)-A.quantile(0.25)
iqr

values    5.5
dtype: float64

In [2461]:

#IQR
#using numpy
IQR = np.quantile(B,0.75)-np.quantile(B,0.25)
IQR

5.5

## QD

In [2462]:
#QD
#using pandas
qd =iqr/2
qd

values    2.75
dtype: float64

In [2463]:

#QD
#using numpy
QD = IQR/2
QD


2.75

# Example 4

## Measure of central tendency

In [2464]:
#created the list into a table format
import pandas as pd
A=pd.DataFrame(data={'values': [1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20]})
A

values
0        1
1        2
2        3
3        1
4        2
5        3
6        4
7        2
8        3
9        5
10       6
11       7
12       8
13       8
14       9
15       8
16       9
17      10
18      12
19      20
20      20
21      20
22      20

In [2465]:
#mean using pandas
A.mean()

# To show answer

values    7.956522
dtype: float64

In [2466]:
A.describe()

values
count  23.000000
mean    7.956522
std     6.427768
min     1.000000
25%     3.000000
50%     7.000000
75%     9.500000
max    20.000000

In [2467]:
#mean 

import numpy as np
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20]

#using numpy
np.mean(B)

7.956521739130435

In [2468]:
print("mean : ", np.mean(B))

mean :  7.956521739130435


In [2469]:
#median
#using pandas
A.median()

values    7.0
dtype: float64

In [2470]:
A.describe()

values
count  23.000000
mean    7.956522
std     6.427768
min     1.000000
25%     3.000000
50%     7.000000
75%     9.500000
max    20.000000

In [2471]:
#median
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20]

#using numpy
np.median(B)

7.0

In [2472]:
print("median : ", np.median(B))

median :  7.0


In [2473]:
#using pandas
A.mode()  

values
0      20

In [2474]:
#mode
#numpy does not has an attribute mode

In [2475]:
#descriptive statistics
#measure of dispersion
#variance and std deviation

## Measure of Dispersion

### Variance

In [2476]:
#variance
A.var()

values    41.316206
dtype: float64

In [2477]:
#variance

In [2478]:
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20]

#using numpy
np.var(B)
     

39.519848771266545

In [2479]:

print("Variance : ", np.var(B))

Variance :  39.519848771266545


## Standard deviation

In [2480]:
#using pandas
A.std()

values    6.427768
dtype: float64

In [2481]:

#standard deviation
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20]

#using numpy
np.std(B)

6.286481430121825

In [2482]:

print("Variance : ", np.std(B))

Variance :  6.286481430121825


# 5 number Summary


Minimum


1st quartile -Q1


2nd quartile -Q2(Median)



3rd quartile -Q3


Maximum


### Minimum

In [2483]:
#Minimum using pandas

A.min() 


values    1
dtype: int64

In [2484]:

#Minimum
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20]

#using numpy
np.min(B)

1

In [2485]:

print("Minimum : ", np.min(B))

Minimum :  1


## Quartiles

In [2486]:
#using pandas
A.quantile([0.25,0.50,0.75]) 

values
0.25     3.0
0.50     7.0
0.75     9.5

In [2487]:

A.describe()

values
count  23.000000
mean    7.956522
std     6.427768
min     1.000000
25%     3.000000
50%     7.000000
75%     9.500000
max    20.000000

In [2488]:

#quartiles
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20]

#using numpy
np.quantile(B,[0.25,0.50,0.75])

array([3. , 7. , 9.5])

In [2489]:

print("Q1 : ", np.quantile(B,0.25),
      "Q2 : ", np.quantile(B,0.50),
      "Q3 : ", np.quantile(B,0.75))

Q1 :  3.0 Q2 :  7.0 Q3 :  9.5


## Maximum

In [2490]:

#using pandas
A.max()  

values    20
dtype: int64

In [2491]:
#Maximum
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20]

#using numpy
np.max(B)

20

In [2492]:
print("Maximum : ", np.max(B))

Maximum :  20


## Range

In [2493]:
#using pandas
Range = A.max()-A.min()
Range
     

values    19
dtype: int64

In [2494]:

#Range
#using numpy

Ran=np.max(B) - np.min(B)
Ran

19

## IQR

In [2495]:
#using pandas
iqr=A.quantile(0.75)-A.quantile(0.25)
iqr

values    6.5
dtype: float64

In [2496]:

#IQR
#using numpy
IQR = np.quantile(B,0.75)-np.quantile(B,0.25)
IQR

6.5

## QD

In [2497]:
#QD
#using pandas
qd =iqr/2
qd

values    3.25
dtype: float64

In [2498]:

#QD
#using numpy
QD = IQR/2
QD


3.25

# Example 5

## Measure of central tendency

In [2499]:
#created the list into a table format
import pandas as pd
A=pd.DataFrame(data={'values': [1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35]})
A

values
0        1
1        2
2        3
3        1
4        2
5        3
6        4
7        2
8        3
9        5
10       6
11       7
12       8
13       8
14       9
15       8
16       9
17      10
18      12
19      20
20      20
21      20
22      20
23      35

In [2500]:
#mean using pandas
A.mean()

# To show answer

values    9.083333
dtype: float64

In [2501]:
A.describe()

values
count  24.000000
mean    9.083333
std     8.366167
min     1.000000
25%     3.000000
50%     7.500000
75%    10.500000
max    35.000000

In [2502]:
#mean 

import numpy as np
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35]

#using numpy
np.mean(B)

9.083333333333334

In [2503]:
print("mean : ", np.mean(B))

mean :  9.083333333333334


In [2504]:
#median
#using pandas
A.median()

values    7.5
dtype: float64

In [2505]:
A.describe()

values
count  24.000000
mean    9.083333
std     8.366167
min     1.000000
25%     3.000000
50%     7.500000
75%    10.500000
max    35.000000

In [2506]:
#median
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35]

#using numpy
np.median(B)

7.5

In [2507]:
print("median : ", np.median(B))

median :  7.5


In [2508]:
#using pandas
A.mode()  

values
0      20

In [2509]:
#mode
#numpy does not has an attribute mode

In [2510]:
#descriptive statistics
#measure of dispersion
#variance and std deviation

## Measure of Dispersion

### Variance

In [2511]:
#variance
A.var()




values    69.992754
dtype: float64

In [2512]:

#variance

In [2513]:
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35]

#using numpy
np.var(B)
     

67.07638888888889

In [2514]:

print("Variance : ", np.var(B))

Variance :  67.07638888888889


## Standard deviation

In [2515]:
#using pandas
A.std()

values    8.366167
dtype: float64

In [2516]:

#standard deviation
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35]

#using numpy
np.std(B)

8.190017636665313

In [2517]:

print("Variance : ", np.std(B))

Variance :  8.190017636665313


# 5 number Summary


Minimum


1st quartile -Q1


2nd quartile -Q2(Median)



3rd quartile -Q3


Maximum


### Minimum

In [2518]:
#Minimum using pandas

A.min() 


values    1
dtype: int64

In [2519]:

#Minimum
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35]

#using numpy
np.min(B)

1

In [2520]:

print("Minimum : ", np.min(B))

Minimum :  1


## Quartiles

In [2521]:
#using pandas
A.quantile([0.25,0.50,0.75]) 

values
0.25     3.0
0.50     7.5
0.75    10.5

In [2522]:

A.describe()

values
count  24.000000
mean    9.083333
std     8.366167
min     1.000000
25%     3.000000
50%     7.500000
75%    10.500000
max    35.000000

In [2523]:

#quartiles
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35]

#using numpy
np.quantile(B,[0.25,0.50,0.75])

array([ 3. ,  7.5, 10.5])

In [2524]:

print("Q1 : ", np.quantile(B,0.25),
      "Q2 : ", np.quantile(B,0.50),
      "Q3 : ", np.quantile(B,0.75))

Q1 :  3.0 Q2 :  7.5 Q3 :  10.5


## Maximum

In [2525]:

#using pandas
A.max()  

values    35
dtype: int64

In [2526]:
#Maximum
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35]

#using numpy
np.max(B)

35

In [2527]:
print("Maximum : ", np.max(B))

Maximum :  35


## Range

In [2528]:
#using pandas
Range = A.max()-A.min()
Range
     

values    34
dtype: int64

In [2529]:

#Range
#using numpy

Ran=np.max(B) - np.min(B)
Ran

34

## IQR

In [2530]:
#using pandas
iqr=A.quantile(0.75)-A.quantile(0.25)
iqr

values    7.5
dtype: float64

In [2531]:

#IQR
#using numpy
IQR = np.quantile(B,0.75)-np.quantile(B,0.25)
IQR

7.5

# Example 6

## Measure of central tendency

In [2532]:
#created the list into a table format
import pandas as pd
A=pd.DataFrame(data={'values': [1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35,55,55]})
A

values
0        1
1        2
2        3
3        1
4        2
5        3
6        4
7        2
8        3
9        5
10       6
11       7
12       8
13       8
14       9
15       8
16       9
17      10
18      12
19      20
20      20
21      20
22      20
23      35
24      55
25      55

In [2533]:
#mean using pandas
A.mean()

# To show answer

values    12.615385
dtype: float64

In [2534]:
A.describe()

values
count  26.000000
mean   12.615385
std    14.835301
min     1.000000
25%     3.000000
50%     8.000000
75%    18.000000
max    55.000000

In [2535]:
#mean 

import numpy as np
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35,55,55]

#using numpy
np.mean(B)

C:\Users\user\anaconda3\lib\site-packages\IPython\core\displayhook.py:275: UserWarning: Output cache limit (currently 1000 entries) hit.
Flushing oldest 200 entries.
  warn('Output cache limit (currently {sz} entries) hit.\n'


12.615384615384615

In [2536]:
print("mean : ", np.mean(B))

mean :  12.615384615384615


In [2537]:
#median
#using pandas
A.median()

values    8.0
dtype: float64

In [2538]:
A.describe()

values
count  26.000000
mean   12.615385
std    14.835301
min     1.000000
25%     3.000000
50%     8.000000
75%    18.000000
max    55.000000

In [2539]:
#median
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35,55,55]

#using numpy
np.median(B)

8.0

In [2540]:
print("median : ", np.median(B))

median :  8.0


In [2541]:
#using pandas
A.mode()  

values
0      20

In [2542]:
#mode
#numpy does not has an attribute mode

In [2543]:
#descriptive statistics
#measure of dispersion
#variance and std deviation

## Measure of Dispersion

### Variance

In [2544]:
#variance
A.var()




values    220.086154
dtype: float64

In [2545]:

#variance

In [2546]:
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35,55,55]

#using numpy
np.var(B)
     

211.62130177514794

In [2547]:

print("Variance : ", np.var(B))

Variance :  211.62130177514794


## Standard deviation

In [2548]:
#using pandas
A.std()

values    14.835301
dtype: float64

In [2549]:

#standard deviation
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35,55,55]

#using numpy
np.std(B)

14.547209415387817

In [2550]:

print("Variance : ", np.std(B))

Variance :  14.547209415387817


# 5 number Summary


Minimum


1st quartile -Q1


2nd quartile -Q2(Median)



3rd quartile -Q3


Maximum


### Minimum

In [2551]:
#Minimum using pandas

A.min() 


values    1
dtype: int64

In [2552]:

#Minimum
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35,55,55]

#using numpy
np.min(B)

1

In [2553]:

print("Minimum : ", np.min(B))

Minimum :  1


## Quartiles

In [2554]:
#using pandas
A.quantile([0.25,0.50,0.75]) 

values
0.25     3.0
0.50     8.0
0.75    18.0

In [2555]:

A.describe()

values
count  26.000000
mean   12.615385
std    14.835301
min     1.000000
25%     3.000000
50%     8.000000
75%    18.000000
max    55.000000

In [2556]:

#quartiles
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35,55,55]

#using numpy
np.quantile(B,[0.25,0.50,0.75])

array([ 3.,  8., 18.])

In [2557]:

print("Q1 : ", np.quantile(B,0.25),
      "Q2 : ", np.quantile(B,0.50),
      "Q3 : ", np.quantile(B,0.75))

Q1 :  3.0 Q2 :  8.0 Q3 :  18.0


## Maximum

In [2558]:

#using pandas
A.max()  

values    55
dtype: int64

In [2559]:
#Maximum
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35,55,55]

#using numpy
np.max(B)

55

In [2560]:
print("Maximum : ", np.max(B))

Maximum :  55


## Range

In [2561]:
#using pandas
Range = A.max()-A.min()
Range
     

values    54
dtype: int64

In [2562]:

#Range
#using numpy

Ran=np.max(B) - np.min(B)
Ran

54

## IQR

In [2563]:
#using pandas
iqr=A.quantile(0.75)-A.quantile(0.25)
iqr

values    15.0
dtype: float64

In [2564]:

#IQR
#using numpy
IQR = np.quantile(B,0.75)-np.quantile(B,0.25)
IQR

15.0

# Example 7

## Measure of central tendency

In [2565]:
#created the list into a table format
import pandas as pd
A=pd.DataFrame(data={'values': [1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35,55,55,60,65]})
A

values
0        1
1        2
2        3
3        1
4        2
5        3
6        4
7        2
8        3
9        5
10       6
11       7
12       8
13       8
14       9
15       8
16       9
17      10
18      12
19      20
20      20
21      20
22      20
23      35
24      55
25      55
26      60
27      65

In [2566]:
#mean using pandas
A.mean()

# To show answer

values    16.178571
dtype: float64

In [2567]:
A.describe()

values
count  28.000000
mean   16.178571
std    19.375535
min     1.000000
25%     3.000000
50%     8.000000
75%    20.000000
max    65.000000

In [2568]:
#mean 

import numpy as np
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35,55,55,60,65]

#using numpy
np.mean(B)

16.178571428571427

In [2569]:
print("mean : ", np.mean(B))

mean :  16.178571428571427


In [2570]:
#median
#using pandas
A.median()

values    8.0
dtype: float64

In [2571]:
A.describe()

values
count  28.000000
mean   16.178571
std    19.375535
min     1.000000
25%     3.000000
50%     8.000000
75%    20.000000
max    65.000000

In [2572]:
#median
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35,55,55,60,65]

#using numpy
np.median(B)

8.0

In [2573]:
print("median : ", np.median(B))

median :  8.0


In [2574]:
#using pandas
A.mode()  

values
0      20

In [2575]:
#mode
#numpy does not has an attribute mode

In [2576]:
#descriptive statistics
#measure of dispersion
#variance and std deviation

## Measure of Dispersion

### Variance

In [2577]:
#variance
A.var()




values    375.411376
dtype: float64

In [2578]:

#variance

In [2579]:
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35,55,55,60,65]

#using numpy
np.var(B)
     

362.0038265306122

In [2580]:

print("Variance : ", np.var(B))

Variance :  362.0038265306122


## Standard deviation

In [2581]:
#using pandas
A.std()

values    19.375535
dtype: float64

In [2582]:

#standard deviation
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35,55,55,60,65]

#using numpy
np.std(B)

19.026398149166653

In [2583]:

print("Variance : ", np.std(B))

Variance :  19.026398149166653


# 5 number Summary


Minimum


1st quartile -Q1


2nd quartile -Q2(Median)



3rd quartile -Q3


Maximum


### Minimum

In [2584]:
#Minimum using pandas

A.min() 


values    1
dtype: int64

In [2585]:

#Minimum
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35,55,55,60,65]

#using numpy
np.min(B)

1

In [2586]:

print("Minimum : ", np.min(B))

Minimum :  1


## Quartiles

In [2587]:
#using pandas
A.quantile([0.25,0.50,0.75]) 

values
0.25     3.0
0.50     8.0
0.75    20.0

In [2588]:

A.describe()

values
count  28.000000
mean   16.178571
std    19.375535
min     1.000000
25%     3.000000
50%     8.000000
75%    20.000000
max    65.000000

In [2589]:

#quartiles
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35,55,55,60,65]

#using numpy
np.quantile(B,[0.25,0.50,0.75])

array([ 3.,  8., 20.])

In [2590]:

print("Q1 : ", np.quantile(B,0.25),
      "Q2 : ", np.quantile(B,0.50),
      "Q3 : ", np.quantile(B,0.75))

Q1 :  3.0 Q2 :  8.0 Q3 :  20.0


## Maximum

In [2591]:

#using pandas
A.max()  

values    65
dtype: int64

In [2592]:
#Maximum
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35,55,55,60,65]

#using numpy
np.max(B)

65

In [2593]:
print("Maximum : ", np.max(B))

Maximum :  65


## Range

In [2594]:
#using pandas
Range = A.max()-A.min()
Range
     

values    64
dtype: int64

In [2595]:

#Range
#using numpy

Ran=np.max(B) - np.min(B)
Ran

64

## IQR

In [2596]:
#using pandas
iqr=A.quantile(0.75)-A.quantile(0.25)
iqr

values    17.0
dtype: float64

In [2597]:

#IQR
#using numpy
IQR = np.quantile(B,0.75)-np.quantile(B,0.25)
IQR

17.0

# Example 8

## Measure of central tendency

In [2598]:
#created the list into a table format
import pandas as pd
A=pd.DataFrame(data={'values': [1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35,55,55,60,65,100]})
A

values
0        1
1        2
2        3
3        1
4        2
5        3
6        4
7        2
8        3
9        5
10       6
11       7
12       8
13       8
14       9
15       8
16       9
17      10
18      12
19      20
20      20
21      20
22      20
23      35
24      55
25      55
26      60
27      65
28     100

In [2599]:
#mean using pandas
A.mean()

# To show answer

values    19.068966
dtype: float64

In [2600]:
A.describe()

values
count   29.000000
mean    19.068966
std     24.582123
min      1.000000
25%      3.000000
50%      8.000000
75%     20.000000
max    100.000000

In [2601]:
#mean 

import numpy as np
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35,55,55,60,65,100]

#using numpy
np.mean(B)

19.06896551724138

In [2602]:
print("mean : ", np.mean(B))

mean :  19.06896551724138


In [2603]:
#median
#using pandas
A.median()

values    8.0
dtype: float64

In [2604]:
A.describe()

values
count   29.000000
mean    19.068966
std     24.582123
min      1.000000
25%      3.000000
50%      8.000000
75%     20.000000
max    100.000000

In [2605]:
#median
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35,55,55,60,65,100]

#using numpy
np.median(B)

8.0

In [2606]:
print("median : ", np.median(B))

median :  8.0


In [2607]:
#using pandas
A.mode()  

values
0      20

In [2608]:
#mode
#numpy does not has an attribute mode

In [2609]:
#descriptive statistics
#measure of dispersion
#variance and std deviation

## Measure of Dispersion

### Variance

In [2610]:
#variance
A.var()




values    604.280788
dtype: float64

In [2611]:

#variance

In [2612]:
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35,55,55,60,65,100]

#using numpy
np.var(B)
     

583.4435196195006

In [2613]:

print("Variance : ", np.var(B))

Variance :  583.4435196195006


## Standard deviation

In [2614]:
#using pandas
A.std()

values    24.582123
dtype: float64

In [2615]:

#standard deviation
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35,55,55,60,65,100]

#using numpy
np.std(B)

24.15457554211004

In [2616]:

print("Variance : ", np.std(B))

Variance :  24.15457554211004


# 5 number Summary


Minimum


1st quartile -Q1


2nd quartile -Q2(Median)



3rd quartile -Q3


Maximum


### Minimum

In [2617]:
#Minimum using pandas

A.min() 


values    1
dtype: int64

In [2618]:

#Minimum
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35,55,55,60,65,100]

#using numpy
np.min(B)

1

In [2619]:

print("Minimum : ", np.min(B))

Minimum :  1


## Quartiles

In [2620]:
#using pandas
A.quantile([0.25,0.50,0.75]) 

values
0.25     3.0
0.50     8.0
0.75    20.0

In [2621]:

A.describe()

values
count   29.000000
mean    19.068966
std     24.582123
min      1.000000
25%      3.000000
50%      8.000000
75%     20.000000
max    100.000000

In [2622]:

#quartiles
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35,55,55,60,65,100]

#using numpy
np.quantile(B,[0.25,0.50,0.75])

array([ 3.,  8., 20.])

In [2623]:

print("Q1 : ", np.quantile(B,0.25),
      "Q2 : ", np.quantile(B,0.50),
      "Q3 : ", np.quantile(B,0.75))

Q1 :  3.0 Q2 :  8.0 Q3 :  20.0


## Maximum

In [2624]:

#using pandas
A.max()  

values    100
dtype: int64

In [2625]:
#Maximum
B=[1,2,3,1,2,3,4,2,3,5,6,7,8,8,9,8,9,10,12,20,20,20,20,35,55,55,60,65,100]

#using numpy
np.max(B)

100

In [2626]:
print("Maximum : ", np.max(B))

Maximum :  100


## Range

In [2627]:
#using pandas
Range = A.max()-A.min()
Range
     

values    99
dtype: int64

In [2628]:

#Range
#using numpy

Ran=np.max(B) - np.min(B)
Ran

99

## IQR

In [2629]:
#using pandas
iqr=A.quantile(0.75)-A.quantile(0.25)
iqr

values    17.0
dtype: float64

In [2630]:

#IQR
#using numpy
IQR = np.quantile(B,0.75)-np.quantile(B,0.25)
IQR

17.0